<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12</LangVersion>
    <ApplicationIcon />
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>2.1.0</Version>
    <AssemblyVersion>2.1.0.0</AssemblyVersion>
    <AssemblyTitle>Makou Reactor</AssemblyTitle>
    <Product>Makou Reactor</Product>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MakouReactor.Core\MakouReactor.Core.csproj" />
    <ProjectReference Include="..\MakouReactor.AI\MakouReactor.AI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.2" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
  </ItemGroup>

</Project>
